<a href="https://colab.research.google.com/github/U070Q205/AI/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#numpy
#偉大的龍大大

In [1]:
import pandas as pd
print("pandas version: %s" % pd.__version__)

pandas version: 0.24.2


In [0]:
import pandas as pd
print(“pandas version: %s” % pd.__version__)
import matplotlib
print("matplotlib version: %s" % matplotlib.__version__)
import numpy as np
print("numpy version: %s" % np.__version__)
import sklearn
print("scikit-learn version: %s" % sklearn.__version__)

#建立array(陣列)
###使用np.array()建立陣列

In [2]:
import numpy as np
x = np.array([[1,2.0],[0,0],(1+1j,3.)])
print(x)

[[1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j]]


#使用numpy提供的創建函數直接生成


In [3]:
import numpy as np
x=np.zeros((2, 3))
y=np.arange(2, 3, 0.1) # start, end, step
z=np.linspace(1., 4., 6) # start, end, num
w=np.indices((3, 3))
print(x)
print(y)
print(z)
print(w)


[[0. 0. 0.]
 [0. 0. 0.]]
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
[1.  1.6 2.2 2.8 3.4 4. ]
[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


In [4]:
import numpy as np

z=np.linspace(1., 4., 6) # start, end, num

print(z)


[1.  1.6 2.2 2.8 3.4 4. ]


In [5]:
import numpy as np

#z=np.linspace(1., 4., 6) # start, end, num
z=np.linspace(2.0, 3.0, num=5)

print(z)

[2.   2.25 2.5  2.75 3.  ]


In [6]:
import numpy as np

#z=np.linspace(1., 4., 6) # start, end, num
z=np.linspace(2.0, 3.0, num=5, endpoint=False)

print(z)

[2.  2.2 2.4 2.6 2.8]


In [7]:
import numpy as np

#z=np.linspace(1., 4., 6) # start, end, num
z=np.linspace(2.0, 3.0, num=5, retstep=True)

print(z)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)


#作業1:下列輸出有何不同?

np.linspace(2.0, 3.0, num=5)

np.linspace(2.0, 3.0, num=5, endpoint=False)

np.linspace(2.0, 3.0, num=5, retstep=True)
參考資料:

https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html

In [8]:
import numpy as np

#z=np.linspace(1., 4., 6) # start, end, num
x=np.linspace(2.0, 3.0, num=5)

y=np.linspace(2.0, 3.0, num=5, endpoint=False)

z=np.linspace(2.0, 3.0, num=5, retstep=True)

print(x)
print(y)
print(z)

[2.   2.25 2.5  2.75 3.  ]
[2.  2.2 2.4 2.6 2.8]
(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)
