<a href="https://colab.research.google.com/github/U070Q205/AI/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#numpy
#偉大的龍大大

In [1]:
import pandas as pd
print("pandas version: %s" % pd.__version__)

pandas version: 0.24.2


In [0]:
import pandas as pd
print(“pandas version: %s” % pd.__version__)
import matplotlib
print("matplotlib version: %s" % matplotlib.__version__)
import numpy as np
print("numpy version: %s" % np.__version__)
import sklearn
print("scikit-learn version: %s" % sklearn.__version__)

#建立array(陣列)
###使用np.array()建立陣列

In [2]:
import numpy as np
x = np.array([[1,2.0],[0,0],(1+1j,3.)])
print(x)

[[1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j]]


#使用numpy提供的創建函數直接生成


In [3]:
import numpy as np
x=np.zeros((2, 3))
y=np.arange(2, 3, 0.1) # start, end, step
z=np.linspace(1., 4., 6) # start, end, num
w=np.indices((3, 3))
print(x)
print(y)
print(z)
print(w)


[[0. 0. 0.]
 [0. 0. 0.]]
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
[1.  1.6 2.2 2.8 3.4 4. ]
[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


In [4]:
import numpy as np

z=np.linspace(1., 4., 6) # start, end, num

print(z)


[1.  1.6 2.2 2.8 3.4 4. ]


In [5]:
import numpy as np

#z=np.linspace(1., 4., 6) # start, end, num
z=np.linspace(2.0, 3.0, num=5)

print(z)

[2.   2.25 2.5  2.75 3.  ]


In [6]:
import numpy as np

#z=np.linspace(1., 4., 6) # start, end, num
z=np.linspace(2.0, 3.0, num=5, endpoint=False)

print(z)

[2.  2.2 2.4 2.6 2.8]


In [7]:
import numpy as np

#z=np.linspace(1., 4., 6) # start, end, num
z=np.linspace(2.0, 3.0, num=5, retstep=True)

print(z)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)


#作業1:下列輸出有何不同?

np.linspace(2.0, 3.0, num=5)

np.linspace(2.0, 3.0, num=5, endpoint=False)

np.linspace(2.0, 3.0, num=5, retstep=True)
參考資料:

https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html

In [8]:
import numpy as np

#z=np.linspace(1., 4., 6) # start, end, num
x=np.linspace(2.0, 3.0, num=5)

y=np.linspace(2.0, 3.0, num=5, endpoint=False)

z=np.linspace(2.0, 3.0, num=5, retstep=True)

print(x)
print(y)
print(z)

[2.   2.25 2.5  2.75 3.  ]
[2.  2.2 2.4 2.6 2.8]
(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)


In [0]:
import numpy as np

a=np.array([[0,1],[2,3]])

a.reshape(1,4)
a.reshape(4,1)


In [10]:
import numpy as np

x = np.arange(2,10).reshape(2,4)
x


array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [11]:
import numpy as np

x = np.arange(2,10).reshape(4,2)
x

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [19]:
import numpy as np

x = np.arange(24).reshape(3,4,2)

x


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [18]:
import numpy as np

x = np.arange(24).reshape(4,3,2)


x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [20]:
import numpy as np

x = np.arange(24).reshape(6,2,2)


x

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [23]:
ar2=np.array([[0,3,5],[2,8,7]]) # 2D array
ar2.shape


(2, 3)

In [24]:
ar2=np.array([[0,3,5],[2,8,7]]) # 2D array
ar2.shape
ar2.ndim


2

In [26]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [27]:
x2 = x.reshape(4,1)
x2

array([[0],
       [1],
       [2],
       [3]])

In [28]:
ar=np.array([np.arange(1,6),np.arange(10,15)]); 
ar


array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [29]:
ar=np.array([np.arange(1,6),np.arange(10,15)]); 
ar
ar.ravel()


array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [30]:
ar=np.array([np.arange(1,6),np.arange(10,15)]); 
ar
ar.T.ravel()


array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

In [31]:
x = np.random.rand(4,2)
x

array([[0.95163229, 0.39201957],
       [0.01014668, 0.72115042],
       [0.1028202 , 0.88759175],
       [0.96793156, 0.72593015]])

In [32]:
x = np.random.rand(4,2)
x

array([[0.77530702, 0.88386957],
       [0.77190928, 0.82635222],
       [0.4138098 , 0.97947442],
       [0.93235176, 0.88845857]])

In [33]:
x = np.random.rand(4,3,2)
x

array([[[0.96860287, 0.19194528],
        [0.92338   , 0.10058948],
        [0.93094116, 0.44467081]],

       [[0.181185  , 0.43005021],
        [0.197726  , 0.18066934],
        [0.00760663, 0.6858386 ]],

       [[0.2600401 , 0.56730694],
        [0.48514691, 0.7604357 ],
        [0.27510559, 0.5470777 ]],

       [[0.49548638, 0.25484183],
        [0.69799258, 0.99048326],
        [0.89165332, 0.21498579]]])

In [40]:
x = np.random.randint(1,size=5)   # 返回[0,1)之間的整數，所以只有0
                                                     #  array([0, 0, 0, 0, 0])
y = np.random.randint(1,5)           # 返回1个[1,5)时间的随机整数
                                                     # 4
z = np.random.randint(-5,5,size=(2,2))

                                                   # array([[ 2, -1],
                                                                 #[ 2,  0]])
x



array([0, 0, 0, 0, 0])

In [41]:
y = np.random.randint(1,5)           # 返回1个[1,5)时间的随机整数
                                                     # 4
y

1

In [42]:
z = np.random.randint(-5,5,size=(2,2))

                                                   # array([[ 2, -1],
                                                                 #[ 2,  0]])
z

array([[ 0, -3],
       [ 1,  1]])

In [43]:
np.random.seed(0)
np.random.rand(5)


array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [44]:
np.random.seed(1676)
np.random.rand(5)


array([0.39983389, 0.29426895, 0.89541728, 0.71807369, 0.3531823 ])

In [45]:
np.random.seed(1676)
np.random.rand(5)


array([0.39983389, 0.29426895, 0.89541728, 0.71807369, 0.3531823 ])

In [47]:
import numpy as np
np.random.seed(0) 

x1 = np.random.randint(10, size=6) 
x2 = np.random.randint(10, size=(3, 4)) 
x3 = np.random.randint(10, size=(3, 4, 5))  
print(x1)
print(x2)
print(x3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [49]:
x1 = np.random.randint(10, size=6) 
x1

array([3, 7, 5, 5, 0, 1])

In [50]:
x2 = np.random.randint(10, size=(3, 4))
x2

array([[5, 9, 3, 0],
       [5, 0, 1, 2],
       [4, 2, 0, 3]])

In [51]:
x3 = np.random.randint(10, size=(3, 4, 5))  
x3

array([[[2, 0, 7, 5, 9],
        [0, 2, 7, 2, 9],
        [2, 3, 3, 2, 3],
        [4, 1, 2, 9, 1]],

       [[4, 6, 8, 2, 3],
        [0, 0, 6, 0, 6],
        [3, 3, 8, 8, 8],
        [2, 3, 2, 0, 8]],

       [[8, 3, 8, 2, 8],
        [4, 3, 0, 4, 3],
        [6, 9, 8, 0, 8],
        [5, 9, 0, 9, 6]]])

In [52]:
ar9 = np.eye(3);
ar9


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
ar10=np.diag((2,1,4,6));
ar10


array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [54]:
import numpy as np
np.array([range(i, i + 3) for i in [2, 4, 6]])


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [55]:
import numpy as np
np.array([range(i, i + 3) for i in [2, 4, 6]])


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

#作業:下列答案為何?
##np.tile(np.array([[1,2],[6,7]]),3)
##np.tile(np.array([[1,2],[6,7]]),(2,2))


In [56]:
np.tile(np.array([[1,2],[6,7]]),3)


array([[1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7]])

In [57]:
np.tile(np.array([[1,2],[6,7]]),(2,2))


array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

In [60]:
import numpy as np
x1 = np.random.randint(10, size=6)
x1 


array([5, 3, 1, 8, 0, 4])

In [62]:
import numpy as np
x1 = np.random.randint(10, size=6)
x1[0]


9

In [63]:
import numpy as np
x1 = np.random.randint(10, size=6)
x1[-2]


6

In [64]:
import numpy as np
x1 = np.random.randint(10, size=6)
x1[-1]


2

In [65]:
import numpy as np
x2 = np.random.randint(10, size=(3, 4)) 
x2 


array([[3, 6, 3, 6],
       [5, 7, 0, 8],
       [4, 6, 5, 8]])